### ISSUE TITLE
Ingest recently released missing 30m SRTM data

### ISSUE THREAD

**Issue by wncampbell** [ngageoint/mrgeo#170]
Looks like the remaining SRTM 30m data has been released. Let's get it and ingest, perhaps filling any remaining small gaps with Aster as before.

**Comment by djohnson729** [comment]
This data has been ingested to s3://mrgeo/images/srtm-v3-30m however it still needs some massaging because the min value after ingest is -11600 meters and the max value is 22830 meters. Tim took a look at the areas with data above the real min/max elevations on the earth, and it's concentrated to a specific area and just looks wrong. In that area, the old v2 SRTM layer had nodata there.

So we propose running a "con" statement to set any pixels to nodata if their value below the true min elevation or above the true max elevation.
