### ISSUE TITLE
Refactor MrsPyramidRecordReader

### ISSUE THREAD

**Issue by ttislerdg** [ngageoint/mrgeo#176]
After the switch to spark, it looks like most of the MrsPyramidRecordReaders can be simplified  to eliminate a lot of the custom code to do thinks like blank tile filling.

The only thing the record reader should do any more is read the data from the appropriate data source.

**Comment by djohnson729** [comment]
To expand on @ttislerdg comments, the MrsPyramidSimpleInputFormat has two inner classes that used to fill in blank tiles prior to the transition from map/reduce to Spark. That capability is no longer used, and should be removed - including the includeEmptyTiles flag in TiledInputFormatContext.

All of static "setup" functions in MrsImageDataProvider should be removed because they are not used any more.

MrsPyramidInputFormat, MrsImagePyramidInput, MrsPyramidRecordReader and MrsImagePyramidRecordReader can all be removed since they are no longer used.

Get rid of the two AllTiles inner classes from MrsImagePyramidSimpleRecordReader.

Rename MrsPyramidSimpleInputFormat to MrsPyramidInputFormat. Rename MrsImagePyramidSimpleInputFormat to MrsPyramidInputFormat. Rename MrsPyramidSimpleRecordReader to MrsPyramidRecordReader. Rename MrsImagePyramidSimpleRecordReader to MrsImagePyramidRecordReader.

**Comment by djohnson729** [comment]
We also believe that these changes will fix a problem that we are currently seeing when building a pyramid on an image stored in S3 within EMR.

**Comment by drew-bower** [comment]
Potential impact on performance?

**Comment by djohnson729** [comment]
I don't anticipate much of any impact on performance. Most of this is removing unused code.

**Comment by drew-bower** [comment]
And possibly increased stability.

**Comment by djohnson729** [comment]
Yes, and simplified code, and most importantly for the short-term, we expect it will address our current problem with build pyramid.
