### ISSUE TITLE
Provide details on which web servers mrgeo will run on

### ISSUE THREAD

**Issue by willtemperley** [ngageoint/mrgeo#23]
It would be great if someone could provide details of which webservers mrgeo can be run on.  I've tried a few and I'm not having much luck. With JBOSS AS 7 and 8  I get "Failed to start service jboss.module.service."deployment.mrgeo-0.5.0-cdh5.1.3-SNAPSHOT-cdh5.1.3.war".main" and with JBOSS AS6 I get issues with Java 7 compatibility. 

If someone could give me some pointers I would be happy to write a wiki page on the WAR deployment process and requirements.

**Comment by djohnson729** [comment]
I just spent some time deploying to tomcat7, but I had to make a couple of fixes (which I just pushed). Also, in order to startup the web services, the MRGEO_HOME env var must be set. I don't have a JBoss instance easily available to me to try, but I can help you with your deployment to JBoss after you grab these changes and figure out how to define MRGEO_HOME in that environment.

**Comment by djohnson729** [comment]
I just pushed changes for issue #29 to provide an easy way to launch the MrGeo web services that might be of interest to you for a quick way of getting started using the web services.

**Comment by ttislerdg** [comment]
OBE
