### ISSUE TITLE
MrGeo WMS Issues in Qgis

### ISSUE THREAD

**Issue by bpeizer** [ngageoint/mrgeo#506]
Currently the tobler layers, slope-gradient-30m and osm-raods-kph-30m do not show correctly in Qgis, they render as solid black boxes.

**Comment by ttislerdg** [comment]
These 3 layers have some outlier values that cause the default black->white color scale to cluster the colors toward the lower end (black).  We've created other scales to display them better. 

If they also don't already have one, we can set a default color scale tag on the pyramids themselves to force the correct scale instead of the black->white one
