### ISSUE TITLE
Map Algebra Crop operation erroneous results

### ISSUE THREAD

**Issue by wncampbell** [ngageoint/mrgeo#52]
The output of the crop operation results in a layer with a number of tiles either missing or shifted east/west. To reproduce pass any global layer into mapalgebra crop, build pyramids and view result.

**Comment by djohnson729** [comment]
This does not seem to be a problem anymore. I performed an Africa clip against s3://mrgeo/images/aster-30m, and I got the following result (as viewed through QGIS WMS). I think this problem was likely solved by the recent changes to splits files. Nathan, can you please confirm and close this issue?

![image](https://cloud.githubusercontent.com/assets/7021622/8849819/c04efd7a-3110-11e5-9f27-5ee5c9a058cc.png)

**Comment by wncampbell** [comment]
Confirmed
