### ISSUE TITLE
Resolve dependency on input dataset tile scheme

### ISSUE THREAD

**Issue by wncampbell** [ngageoint/mrgeo#63]
Once the multiplier in mrgeo.conf is set correctly, ingest works perfectly for aster and srtm tiled datasources. However, I've not been able to ingest any other data sources including global landcover and tiled geotiffs of srtm water bodies:
- Single 300m, ~300mb globcover raster
- Tiled 300m globcover raster
- Tiled, resampled 30m globcover raster
- Tried the above with various multiplier settings - 2,4,8,12,16,32

**Comment by djohnson729** [comment]
The idea here is there are memory problems during ingest when the source images are large because GDAL has to load the entire source image into memory at once, and then we need another copy of the image in memory in order re-project it to WGS84.

One thing we can do to alleviate that is to re-project portions of the image at once so we don't have to store the full source image twice in memory. This would require determining the bounds of the MrGeo tile we are working on, and clip the source image to that tile's bounds (including a buffer around it that is needed for the re-project). This would have to be done for each MrGeo tile that the source image is ingested into.

**Comment by djohnson729** [comment]
This problem is more difficult than it sounds. Re-projecting the source image as a whole, then chunking it in MrGeo sized tiles is the most straightforward approach because it eliminates round-off errors that can happen for each tile when mapping source pixels to destination pixels. It re-projects the entire source image, and then cuts out individual tiles of the proper size by performing pixel math in the pixel space of the re-projected image.

**Comment by ttislerdg** [comment]
Another option is to reproject the image to a tmp file on disk, then use that image to create the tiles.
